version: "3"

services:
  neo4j:
    image: neo4j:5.26-community
    ports:
      - 7474:7474
      - 7373:7373
      - 7687:7687
    environment:
      - NEO4J_AUTH
    healthcheck:
      test: curl --fail http://localhost:7474 || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  testneo4j:
    image: neo4j:5-community
    ports:
      - 8474:7474
      - 8373:7373
      - 8687:7687
    environment:
      - NEO4J_AUTH=${TEST_NEO4J_AUTH}
    healthcheck:
      test: curl --fail http://localhost:8474 || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  testmemgraph:
    image: memgraph/memgraph:latest
    ports:
      - 9687:7687
      - 7444:7444
    command: ["--log-level=TRACE"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    environment:
      - MEMGRAPH_USER=${TEST_MEMGRAPH_USER}
      - MEMGRAPH_PASSWORD=${TEST_MEMGRAPH_PASSWORD}
