name: ontolocy-examples-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - ontolocy
      - networkx
      - ipydatagrid
      - ipysigma
      - yfiles_jupyter_graphs
